-- liquibase formatted sql
-- changeset anton:insert-object-to-generator-001

INSERT INTO objects (key_name, eng_name, rus_name, image_path)
VALUES ('Anchor_bolt_with_hook_HG', 'Sleeve Anchor With Hook Bolt,Hex Nut And Washer,Yellow Zinc Plated',
        'Анкерный болт с крюком HG', 'Anchor_bolt_with_hook_HG.png'),
       ('Anchor_wedge_MAN', 'Ceiling Anchor,White Zinc Plated', 'Анкер-клин MAN',
        'Anchor_wedge_MAN.png'),
       ('DIN763_chain_LONG_link', 'DIN763 Chain With Long Links, Reel packing', 'DIN763 цепь, длинное звено',
        'DIN763_chain_LONG_link.png'),
       ('DIN766_chain_SHORT_link', 'DIN766 Chain With Short Links, Reel packing', 'DIN766 цепь, короткое звено',
        'DIN766_chain_SHORT_link.png'),
       ('DIN_3055_braided_rope', 'DIN3055 Steel Wire Rope in PVC, 6x7+FC, Reel packing',
        'DIN 3055 Трос в оплетке (6x7)', 'DIN_3055_braided_rope.png'),
       ('DIN_3055_rope_without_braid', 'DIN3055 Steel Wire Rope, 6x7+FC, Reel packing', 'Трос без оплетки',
        'DIN_3055_rope_without_braid.png'),
       ('screw_for_parquet', 'Torx drive timber screws, tim head with 6 ribs, shank with u-thread, self drilling point',
        'Шуруп для полов и паркета', 'screw_for_parquet.png'),
       ('screws_Fluegel_zinc', 'Cross recessed countersunk head drilling screw, BSD, with wings',
        'Саморез "Флюгель", цинк', 'screws_Fluegel_zinc.png'),
       ('screws_GKD_3_5', 'Phillips Bugle Head Drywall Screw, Coarse thread(3.5)', 'Саморезы гипс/дерево(3.5)',
        'screws_GKD_3.5_AND_3.9_AND_4.2.png'),
       ('screws_GKD_3_9', 'Phillips Bugle Head Drywall Screw, Coarse thread(3.9)', 'Саморезы гипс/дерево(3.9)',
        'screws_GKD_3.5_AND_3.9_AND_4.2.png'),
       ('screws_GKD_4_2', 'Phillips Bugle Head Drywall Screw, Coarse thread(4.2)', 'Саморезы гипс/дерево(4.2)',
        'screws_GKD_3.5_AND_3.9_AND_4.2.png'),
       ('screws_GKM', 'Phillips Bugle Head Drywall Screw, Fine thread', 'Саморезы гипс/металл',
        'screws_GKM.png'),
       ('screws_Press_Washer_SHARP', 'Modified Truss Head Screw, SHARP Point', 'Саморезы Пресс шайба острые',
        'screws_Press_Washer_SHARP.png'),
       ('screws_Press_washer_DRILL', 'Modified Truss Head Screw, Drilling Point', 'Саморезы ПрессШайба сверло',
        'screws_Press_washer_DRILL.png'),
       ('screws_UNIVERSAL_yellow_full_thread', 'Csk Head Pozi Drive Chipboard Screw, Full thread',
        'Саморезы универсальные, желтые, полная резьба',
        'screws_UNIVERSAL_yellow_full_thread.png'),
       ('screws_UNIVERSAL_yellow_part_thread', 'Csk Head Pozi Drive Chipboard Screw, Partial thread',
        'Саморезы универсальные, желтые, неполная резьба',
        'screws_UNIVERSAL_yellow_part_thread.png'),
       ('screws_countersunk_structural_self_tapping', 'TORX DRIVE DOUBLE FLAT HEAD TIMBER SCREW',
        'Конструкционные саморезы потай', 'screws_countersunk_structural_self_tapping.png'),
       ('screws_for_ROOF_zinc_n1', 'Self-drilling Hexagon Head Screw, with black EPDM', 'Кровельный саморез, цинк',
        'screws_for_ROOF_zinc_n1_AND_n3.png'),
       ('screws_for_ROOF_zinc_n3', 'Self-drilling Hexagon Head Screw, with black EPDM', 'Кровельный саморез, цинк',
        'screws_for_ROOF_zinc_n1_AND_n3.png'),
       ('screws_for_metal_DRILL_PHOSPHAT_PMS', 'Pan Framing Head Self Drilling Screw', 'Саморез ПМС, фосфат',
        'screws_for_metal_DRILL_PHOSPHAT_PMS.png'),
       ('screws_for_metal_SHARP_PHOSPHAT_PM', 'Pan Framing Head Self Tapping Screw', 'Саморез ПМ, фосфат',
        'screws_for_metal_SHARP_PHOSPHAT_PM.png'),
       ('screws_for_metal_in_TAPE', 'Collated drywall screws', 'Саморезы гипс/металл в ленте',
        'screws_for_metal_in_TAPE.png'),
       ('screws_reinforced', 'Torx Drive Hex Flange Head Self Tapping Screw,Class 8.8', 'Шуруп усиленный',
        'screws_reinforced.png'),
       ('screws_to_concrete', 'T30 Concrete Screw', 'Шуруп по бетону',
        'screws_to_concrete.png'),
       ('screws_with_disc_head', 'Torx Drive Wafer Head Timber Screw', 'Саморез конструкционный с тарельчатой головкой',
        'screws_with_disc_head.png');
