<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.mgt-group</groupId>
        <artifactId>parent-module</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>javafx</artifactId>

    <repositories>
        <repository>
            <id>openjfx-repo</id>
            <url>https://maven.java.net/content/groups/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- Связь с core -->
        <dependency>
            <groupId>com.mgt-group</groupId>
            <artifactId>core</artifactId>
        </dependency>


        <!-- JavaFX -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <!-- JavaFX Maven Plugin -->
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version> <!-- Используем старую версию -->
                <configuration>
                    <mainClass>com.antonio.docgeneratorfx.SpringJavaFxRunner</mainClass>
<!--                    <options>-->
<!--                        <option>&#45;&#45;module-path</option>-->
<!--                        <option>C:/Users/user/.m2/repository/javafx-sdk-21.0.7</option>-->
<!--                        <option>&#45;&#45;add-modules</option>-->
<!--                        <option>javafx.controls,javafx.fxml</option>-->
<!--                    </options>-->
                </configuration>
            </plugin>
        </plugins>
    </build>







</project>
