spring:
  datasource:
    url: jdbc:sqlite:${app.database.path}/${app.database.name}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        connection.autocommit: true
        format_sql: true
    show-sql: true
    open-in-view: false

app:
  database:
    path: ${user.dir}/data
    name: m-group-trade.db
