spring:
  datasource:
    url: jdbc:sqlite:file:${app.database.path}/${app.database.name}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1  # Важно для SQLite!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        connection.provider_disables_autocommit: true
        format_sql: true
    show-sql: true
    open-in-view: false  # Обязательно для Spring Boot 3+

app:
  database:
    path: ${user.dir}/data
    name: m-group-trade.db