logo_path=resources/images/Mfix.jpg
material=материал
plating=покрытие
function=назначение
importer=ООО "М Групп Торг" РБ, Минский р-н, а/г. Колодищи, ул. Минская, д. 5, пом. 107
shelf_time=срок годности не ограничен
