#spring:
#  datasource:
#    url: jdbc:sqlite:${app.database.path}/${app.database.name}
#    driver-class-name: org.sqlite.JDBC
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.community.dialect.SQLiteDialect
#  liquibase:
#    change-log: classpath:db/changelog/liquibase-changeLog.yaml
#    enabled: true
#    contexts: dev
#
#app:
#  database:
#    path: ${user.dir}/data
#    name: m-group-trade.db
#
#  image:
#    path: ${user.dir}/storage/images/metalware
#  logo:
#    path: ${user.dir}/storage/images/logo
#  common:
#    path: ${user.dir}/storage/common
#
#
##logging:
##  level:
##    root: DEBUG                  # общий уровень логгирования (весь проект)
##    liquibase: TRACE             # детализированно видеть все миграции
##    org.springframework: INFO    # не засорять логи спамом от Spring
##    org.hibernate.SQL: DEBUG     # видеть SQL-запросы от Hibernate
##    org.hibernate.type: TRACE    # видеть параметры, подставляемые в SQL
#
